name:                  lambda-qoi
version:            0.1.0.0
github:              "joseedil/lambda-qoi"
license:            BSD3
author:              "Edil Medeiros"
maintainer:      "jose.edil@gmail.com"
copyright:        "2022 Edil Medeiros"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Codec

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/joseedil/lambda-qoi#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- binary
- vector
- JuicyPixels

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
#- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

default-extensions:
  - OverloadedStrings
  - DeriveGeneric

executables:
  lambda-qoi-exe:
    main:                       Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-qoi

tests:
  lambda-qoi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-qoi
    - tasty
    - tasty-hunit
